server:
  port: 0
  
spring:  application:    name: user-service
    
  data:
    mongodb:      database: user      port: 27017
      host: localhost
      
  main:    allow-bean-definition-overriding: true      
      
eureka:  client:    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
      
  