management:
  endpoints:
    web:
      exposure:
        include: '*'
        
server:    port: 8070
  
spring:  application:    name: product-service
      boot:    admin:      client:        url: http://localhost:9000
        
  h2:    console:      enabled: true
      path: /console
      settings:
        web-allow-others: true
      
  jpa:    hibernate:      ddl-auto: create
    show-sql:  true