server:  port: 8060
spring:  application:    name: movie-service      data:    mongodb:      database: demo-database      port: 27017      host: localhost        main:    allow-bean-definition-overriding: true    
eureka:  client:    service-url:      defaultZone: http://localhost:8761/eureka/      register-with-eureka: true
management:  endpoints:    web:      exposure:        include: '*'         
